const foods = [
  {
    id: 1,
    name: 'Meat Pizza',
    ingredients: 'Mixed Pizza',
    price: 5000,
    image: require('../assets/meatPizza.png'),
    categoryId: 'food_1',
  },
  {
    id: 2,
    name: 'Cheese Pizza',
    ingredients: 'Cheese Pizza',
    price: 3500,
    image: require('../assets/cheesePizza.png'),
    categoryId: 'food_2',
  },
  {
    id: 3,
    name: 'Chicken Burger',
    ingredients: 'Fried Chicken',
    price: 2000,
    image: require('../assets/chickenBurger.png'),
    categoryId: 'food_3',
  },
  {
    id: 4,
    name: 'Sushi Makizushi',
    ingredients: 'Salmon Meat',
    price: 6000,
    image: require('../assets/sushiMakizushi.png'),
    categoryId: 'food_4',
  },
  {
    id: 5,
    name: 'Meat Pizza',
    ingredients: 'Mixed Pizza',
    price: 2500,
    image: require('../assets/meatPizza.png'),
    categoryId: 'food_1',
  },
  {
    id: 6,
    name: 'Cheese Pizza',
    ingredients: 'Cheese Pizza',
    price: 3000,
    image: require('../assets/cheesePizza.png'),
    categoryId: 'food_2',
  },
  {
    id: 7,
    name: 'Chicken Burger',
    ingredients: 'Fried Chicken',
    price: 2000,
    image: require('../assets/chickenBurger.png'),
    categoryId: 'food_3',
  },
  {
    id: 8,
    name: 'Sushi Makizushi',
    ingredients: 'Salmon Meat',
    price: 4000,
    image: require('../assets/sushiMakizushi.png'),
    categoryId: 'food_4',
  },
];

export default foods;
